name: Build and Push Kafka Images

on:
  push:
    branches:
      - main
    paths:
      - 'kafka-deploy/Dockerfile'
      - 'kafka-deploy/*.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Kafka images
      uses: docker/build-push-action@v5
      with:
        context: ./kafka-deploy
        file: ./kafka-deploy/Dockerfile
        push: true
        tags: |
          thapak010189/kafka-custom-image:kafka-broker-latest
          thapak010189/kafka-custom-image:zookeeper-latest
          thapak010189/kafka-custom-image:init-kafka-latest
          thapak010189/kafka-custom-image:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
