# .github/workflows/test-secrets.yml
name: Test Docker Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Check if secrets are available
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME is missing"
          exit 1
        else
          echo "DOCKER_USERNAME is set"
        fi

        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "DOCKER_PASSWORD is missing"
          exit 1
        else
          echo "DOCKER_PASSWORD is set"
        fi
